### ISSUE TITLE
Qtconsole does not follow its output

### ISSUE THREAD

**Issue by DrTobe** [jupyter-vim/jupyter-vim#3]
When I run files in the qtconsole which produce some output, it happens after a while that the output is not visible anymore because the qtconsole does not scroll automatically.

Is there any way to make auto-scroll happen somehow (from vim, without having to switch over to the qtconsole)?

**Comment by wmvanvliet** [comment]
This is fixed in the current master of qtconsole.
https://github.com/jupyter/qtconsole/pull/349

**Comment by DrTobe** [comment]
Nice, thanks for that information. I'll just wait until 4.5.2 will be released for my distro.

**Comment by spring-haru** [comment]
Just half an hour ago I downloaded `jupyter-vim` and started using it. `qtconsole` does not auto-scroll to show the latest input/output.

Neovim 0.4.2
Mac

**Comment by pablocael** [comment]
It is still not working. print commands and plots do not show on qtconsole
